# Generated by Django 5.2.15 on 2026-06-09 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('filiere', models.CharField(choices=[('IR', 'Ingénierie Informatique'), ('IIR', 'Ingénierie Informatique et Réseaux'), ('GSE', 'Génie des Systèmes Embarqués'), ('BI', 'Business Intelligence')], max_length=5, verbose_name='Filière')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('team_members', models.JSONField(blank=True, default=list, verbose_name="Membres de l'équipe")),
                ('document', models.FileField(blank=True, null=True, upload_to='projets/', verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
