# Generated by Django 5.2.15 on 2026-06-09 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('filiere', models.CharField(choices=[('IR', 'Ingénierie Informatique'), ('IIR', 'Ingénierie Informatique et Réseaux'), ('GSE', 'Génie des Systèmes Embarqués'), ('BI', 'Business Intelligence')], max_length=5, verbose_name='Filière')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('OPEN', 'Ouverte'), ('CLOSED', 'Fermée'), ('PUBLISHED', 'Publiée')], default='PLANNED', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermée le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_closed', to=settings.AUTH_USER_MODEL, verbose_name='Fermée par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('jury', models.ManyToManyField(blank=True, related_name='sessions_jury', to=settings.AUTH_USER_MODEL, verbose_name='Membres du jury')),
                ('projets', models.ManyToManyField(blank=True, related_name='sessions', to='website.projet', verbose_name='Projets')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_published', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
            ],
            options={
                'verbose_name': 'Session de vote',
                'verbose_name_plural': 'Sessions de vote',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids en pourcentage', max_digits=5, verbose_name='Poids (%)')),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Note maximale')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='website.sessionvote', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Critère',
                'verbose_name_plural': 'Critères',
                'ordering': ['nom'],
            },
        ),
    ]
