# Generated by Django 5.2.15 on 2026-06-09 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sessionvote_critere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Score total')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('date_vote', models.DateTimeField(auto_now_add=True, verbose_name='Date du vote')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Jury')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='website.projet', verbose_name='Projet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='website.sessionvote', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='NoteParCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.critere', verbose_name='Critère')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.vote', verbose_name='Vote')),
            ],
            options={
                'verbose_name': 'Note par critère',
                'verbose_name_plural': 'Notes par critère',
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('jury', 'projet', 'session'), name='unique_vote_per_jury_project_session'),
        ),
        migrations.AddConstraint(
            model_name='noteparcritere',
            constraint=models.UniqueConstraint(fields=('vote', 'critere'), name='unique_note_per_vote_critere'),
        ),
    ]
