# Generated by Django 5.2.15 on 2026-06-09 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_vote_noteparcritere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_final', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Score final')),
                ('rang', models.IntegerField(verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='website.projet', verbose_name='Projet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='website.sessionvote', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['rang'],
            },
        ),
    ]
