# Generated by Django 5.2.15 on 2026-06-10 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_resultat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], max_length=5, verbose_name='Format')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='website.sessionvote', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-genere_le'],
            },
        ),
    ]
