# Generated by Django 5.2.15 on 2026-06-10 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VOTE', 'Vote'), ('CLOSE', 'Fermeture'), ('PUBLISH', 'Publication'), ('VALIDATE', 'Validation')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID Objet')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': "Journaux d'actions",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('VOTE_OPEN', 'Session ouverte'), ('VOTE_CLOSED', 'Session fermée'), ('RESULTS_PUBLISHED', 'Résultats publiés'), ('PROJECT_VALIDATED', 'Projet validé'), ('PROJECT_REJECTED', 'Projet rejeté')], default='INFO', max_length=30, verbose_name='Type')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('lien', models.CharField(blank=True, help_text='URL optionnelle', max_length=200, verbose_name='Lien')),
                ('lu', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
