from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('password-change/', views.password_change_view, name='password_change'),
    path('token-refresh/', views.refresh_token_view, name='token_refresh'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password_reset_form.html',
             email_template_name='password_reset_email.txt',
             subject_template_name='password_reset_subject.txt',
             success_url=reverse_lazy('password_reset_done'),
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html',
         ),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
             success_url=reverse_lazy('password_reset_complete'),
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html',
         ),
         name='password_reset_complete'),
    path('projects/', views.project_list_view, name='project_list'),
    path('projects/create/', views.project_create_view, name='project_create'),
    path('projects/<int:pk>/', views.project_detail_view, name='project_detail'),
    path('projects/<int:pk>/edit/', views.project_edit_view, name='project_edit'),
    path('projects/<int:pk>/submit/', views.project_submit_view, name='project_submit'),
    path('projects/<int:pk>/validate/', views.project_validate_view, name='project_validate'),
    path('projects/<int:pk>/delete/', views.project_delete_view, name='project_delete'),
    path('sessions/', views.session_list_view, name='session_list'),
    path('sessions/create/', views.session_create_view, name='session_create'),
    path('sessions/<int:pk>/', views.session_detail_view, name='session_detail'),
    path('sessions/<int:pk>/criteria/', views.session_criteria_view, name='session_criteria'),
    path('sessions/<int:pk>/assign-jury/', views.session_assign_jury_view, name='session_assign_jury'),
    path('sessions/<int:pk>/assign-projets/', views.session_assign_projets_view, name='session_assign_projets'),
    path('sessions/<int:pk>/open/', views.session_open_view, name='session_open'),
    path('vote/', views.voting_dashboard_view, name='voting_dashboard'),
    path('vote/<int:session_pk>/<int:projet_pk>/', views.vote_project_view, name='vote_project'),
    path('vote/<int:session_pk>/summary/', views.vote_session_summary_view, name='vote_summary'),
    path('sessions/<int:pk>/close/', views.session_close_view, name='session_close'),
    path('sessions/<int:pk>/results/', views.session_results_view, name='session_results'),
    path('sessions/<int:pk>/publish/', views.session_publish_view, name='session_publish'),
    path('results/', views.results_public_view, name='results_public'),
    path('sessions/<int:pk>/report/pdf/', views.report_pdf_view, name='report_pdf'),
    path('sessions/<int:pk>/report/csv/', views.report_csv_view, name='report_csv'),
    path('notifications/', views.notifications_view, name='notifications'),
]
